### ISSUE TITLE
danger-swift is incompatible with swift 4.1

### ISSUE THREAD

**Issue by Sega-Zero** [danger/danger-swift#63]
When launching on a machine with xcode 9.3 (swift 4.1) I got this error:
```bash
danger process danger-swift
dyld: Symbol not found: __T0SayxGs9DecodableslWP
  Referenced from: /usr/local/bin/danger-swift
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /usr/local/bin/danger-swift

events.js:165
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:844:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:453:5)
    at _destroy (internal/streams/destroy.js:39:7)
    at Socket._destroy (net.js:548:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:846:10)
script returned exit code 1
```

Probably, https://github.com/RxSwiftCommunity/Action/pull/118 may help to resolve this issue.

**Comment by Sega-Zero** [comment]
@orta may I hope danger-swift rebuild on xcode 9.3 in a reasonable amount of time? :) My PR's are broken atm 😩

**Comment by SD10** [comment]
@Sega-Zero Thanks for raising this issue. It's a community-driven project so there is no set time frame for things being resolved 😕

That being said, this looks like an error on the JS side. Are you sure this is related to Swift 4.1?

**Comment by Sega-Zero** [comment]
Absolutely. It was working great on xcode 9.2 (swift 4) and broke right after the upgrade. The error is thrown on a danger-swift binary, looks like it hasn't been even launched in a proper way, that's why js is throwing an error, I think

**Comment by sunshinejr** [comment]
Basically, there is a problem with Marathon right now, see [#161](https://github.com/JohnSundell/Marathon/pull/161). We'll have to wait until it's done and check if we need to do anything else to make it work.

**Comment by Sega-Zero** [comment]
Looks like we should wait for https://github.com/JohnSundell/Marathon/issues/172 to be resolved too
